global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
        monitor: 'docker-monitoring'

rule_files:
    - "monitor.rules"
    - "host.rules"
    - "containers.rules"

scrape_configs:
    - job_name: 'cadvisor'
      scrape_interval: 5s
      static_configs:
            - targets: ['cadvisor:8080']

    - job_name: 'prometheus'
      scrape_interval: 10s
      static_configs:
            - targets: ['localhost:9090']